/**
 * Prompt Injector - Inject learned insights into prompts
 *
 * Implements the prompt injection mechanism from specs/prompt-learning.md.
 *
 * Supports two injection methods:
 * 1. skill (recommended): Generate a brain-insights skill for analysis sessions
 * 2. agents_file: Modify AGENTS.md directly (affects all sessions)
 */

import type Database from "better-sqlite3";

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

import type { PromptAddition } from "../types/index.js";

import {
  generatePromptAdditionsFromDb,
  formatPromptAdditionsDocument,
  getPromptAdditionsForModel,
  getModelDisplayName,
} from "./prompt-generator.js";

// =============================================================================
// Types
// =============================================================================

export type InjectionMethod = "skill" | "agents_file";
export type InjectionScope = "analysis_only" | "global";

export interface PromptInjectionConfig {
  /** Injection method (default: skill) */
  method?: InjectionMethod;
  /** Injection scope (default: analysis_only) */
  scope?: InjectionScope;
  /** Custom skill directory (default: ~/skills/brain-insights) */
  skillDir?: string;
  /** Custom AGENTS.md path (for testing) */
  agentsFilePath?: string;
  /** Minimum confidence for auto-inclusion (default: 0.7) */
  minConfidence?: number;
  /** Minimum frequency for auto-inclusion (default: 5) */
  minFrequency?: number;
}

export interface InjectionResult {
  success: boolean;
  message: string;
  /** Path to generated/updated file */
  path?: string;
  /** Number of insights included */
  insightCount?: number;
  /** Models with generated content */
  models?: string[];
}

// =============================================================================
// Constants
// =============================================================================

const DEFAULT_MIN_CONFIDENCE = 0.7;
const DEFAULT_MIN_FREQUENCY = 5;
const DEFAULT_SKILL_DIR = path.join(os.homedir(), "skills", "brain-insights");
const AGENTS_FILE_PATH = path.join(os.homedir(), ".pi", "agent", "AGENTS.md");

// Markers for AGENTS.md section
const AGENTS_MARKER_START = "<!-- pi-brain-insights -->";
const AGENTS_MARKER_END = "<!-- /pi-brain-insights -->";

// =============================================================================
// Skill Generation
// =============================================================================

/**
 * Generate the brain-insights skill frontmatter
 */
function generateSkillFrontmatter(models: string[]): string {
  const modelList = models.map((m) => getModelDisplayName(m)).join(", ");
  const description =
    models.length > 0
      ? `Learned insights for: ${modelList}. Use for model-specific quirks, effective techniques, and tool usage reminders.`
      : "Learned insights from session analysis (currently empty).";

  return `---
name: brain-insights
description: ${description}
trigger: manual
---`;
}

/**
 * Generate the full brain-insights skill content
 */
export function generateBrainInsightsSkill(
  additions: PromptAddition[]
): string {
  const models = additions.map((a) => a.model);
  const frontmatter = generateSkillFrontmatter(models);

  if (additions.length === 0) {
    return `${frontmatter}

# Model-Specific Insights

No actionable insights have been learned yet.

This skill will be populated as pi-brain analyzes your coding sessions and identifies:
- Model quirks to avoid
- Effective prompting techniques
- Tool usage reminders
`;
  }

  const content = formatPromptAdditionsDocument(additions);

  return `${frontmatter}

${content}

---

*Generated by pi-brain. Run \`pi-brain prompt-learning inject\` to update.*
`;
}

/**
 * Write the brain-insights skill to disk
 */
export function writeBrainInsightsSkill(
  db: Database.Database,
  options: PromptInjectionConfig = {}
): InjectionResult {
  const {
    skillDir = DEFAULT_SKILL_DIR,
    minConfidence = DEFAULT_MIN_CONFIDENCE,
    minFrequency = DEFAULT_MIN_FREQUENCY,
  } = options;

  // Generate additions from database
  const additions = generatePromptAdditionsFromDb(db, {
    minConfidence,
    minFrequency,
  });

  // Generate skill content
  const skillContent = generateBrainInsightsSkill(additions);

  // Ensure skill directory exists
  if (!fs.existsSync(skillDir)) {
    fs.mkdirSync(skillDir, { recursive: true });
  }

  // Write skill file
  const skillPath = path.join(skillDir, "SKILL.md");
  fs.writeFileSync(skillPath, skillContent, "utf8");

  const models = additions.map((a) => a.model);
  const insightCount = additions.reduce(
    (sum, a) => sum + a.sourceInsights.length,
    0
  );

  if (additions.length === 0) {
    return {
      success: true,
      message: "Skill generated (no actionable insights found)",
      path: skillPath,
      insightCount: 0,
      models: [],
    };
  }

  return {
    success: true,
    message: `Skill generated with ${insightCount} insights for ${models.length} model(s)`,
    path: skillPath,
    insightCount,
    models,
  };
}

/**
 * Generate skill content for a specific model
 */
export function generateModelSkill(
  db: Database.Database,
  model: string,
  options: PromptInjectionConfig = {}
): string | null {
  const {
    minConfidence = DEFAULT_MIN_CONFIDENCE,
    minFrequency = DEFAULT_MIN_FREQUENCY,
  } = options;

  const addition = getPromptAdditionsForModel(db, model, {
    minConfidence,
    minFrequency,
  });

  if (!addition) {
    return null;
  }

  return generateBrainInsightsSkill([addition]);
}

// =============================================================================
// AGENTS.md Injection (NOT RECOMMENDED)
// =============================================================================

/**
 * Format insights section for AGENTS.md
 */
function formatAgentsSection(additions: PromptAddition[]): string {
  if (additions.length === 0) {
    return "No insights available yet.";
  }

  return formatPromptAdditionsDocument(additions);
}

/**
 * Update AGENTS.md with insights section
 *
 * WARNING: This affects ALL pi sessions, not just analysis.
 * Use skill-based injection instead.
 */
export function updateAgentsFile(
  db: Database.Database,
  options: PromptInjectionConfig = {}
): InjectionResult {
  const {
    minConfidence = DEFAULT_MIN_CONFIDENCE,
    minFrequency = DEFAULT_MIN_FREQUENCY,
    agentsFilePath = AGENTS_FILE_PATH,
  } = options;

  // Check if AGENTS.md exists
  if (!fs.existsSync(agentsFilePath)) {
    return {
      success: false,
      message: `AGENTS.md not found at ${agentsFilePath}`,
    };
  }

  // Generate additions from database
  const additions = generatePromptAdditionsFromDb(db, {
    minConfidence,
    minFrequency,
  });

  // Read current content
  let content = fs.readFileSync(agentsFilePath, "utf8");

  // Format the insights section
  const insightsSection = formatAgentsSection(additions);
  const fullSection = `${AGENTS_MARKER_START}

## Pi-Brain Learned Insights

${insightsSection}

${AGENTS_MARKER_END}`;

  // Check if markers exist
  if (content.includes(AGENTS_MARKER_START)) {
    // Replace existing section
    const regex = new RegExp(
      `${escapeRegex(AGENTS_MARKER_START)}[\\s\\S]*?${escapeRegex(AGENTS_MARKER_END)}`,
      "g"
    );
    content = content.replace(regex, fullSection);
  } else {
    // Append new section
    content = `${content.trimEnd()}\n\n${fullSection}\n`;
  }

  // Write updated content
  fs.writeFileSync(agentsFilePath, content, "utf8");

  const models = additions.map((a) => a.model);
  const insightCount = additions.reduce(
    (sum, a) => sum + a.sourceInsights.length,
    0
  );

  return {
    success: true,
    message: `AGENTS.md updated with ${insightCount} insights for ${models.length} model(s)`,
    path: agentsFilePath,
    insightCount,
    models,
  };
}

/**
 * Remove insights section from AGENTS.md
 */
export function removeFromAgentsFile(
  options: PromptInjectionConfig = {}
): InjectionResult {
  const { agentsFilePath = AGENTS_FILE_PATH } = options;

  if (!fs.existsSync(agentsFilePath)) {
    return {
      success: true,
      message: "AGENTS.md not found, nothing to remove",
    };
  }

  let content = fs.readFileSync(agentsFilePath, "utf8");

  if (!content.includes(AGENTS_MARKER_START)) {
    return {
      success: true,
      message: "No pi-brain section found in AGENTS.md",
    };
  }

  // Remove the section
  const regex = new RegExp(
    `\\n*${escapeRegex(AGENTS_MARKER_START)}[\\s\\S]*?${escapeRegex(AGENTS_MARKER_END)}\\n*`,
    "g"
  );
  content = content.replace(regex, "\n");

  fs.writeFileSync(agentsFilePath, content, "utf8");

  return {
    success: true,
    message: "Removed pi-brain section from AGENTS.md",
    path: agentsFilePath,
  };
}

// =============================================================================
// Main Injection Function
// =============================================================================

/**
 * Inject insights into prompts using configured method
 */
export function injectInsights(
  db: Database.Database,
  options: PromptInjectionConfig = {}
): InjectionResult {
  const { method = "skill" } = options;

  switch (method) {
    case "skill": {
      return writeBrainInsightsSkill(db, options);
    }
    case "agents_file": {
      return updateAgentsFile(db, options);
    }
    default: {
      return {
        success: false,
        message: `Unknown injection method: ${method}`,
      };
    }
  }
}

/**
 * Remove injected insights
 */
export function removeInjectedInsights(
  options: PromptInjectionConfig = {}
): InjectionResult {
  const { method = "skill", skillDir = DEFAULT_SKILL_DIR } = options;

  switch (method) {
    case "skill": {
      const skillPath = path.join(skillDir, "SKILL.md");
      if (fs.existsSync(skillPath)) {
        fs.unlinkSync(skillPath);
        // Try to remove directory if empty
        try {
          fs.rmdirSync(skillDir);
        } catch {
          // Directory not empty, that's fine
        }
        return {
          success: true,
          message: "Removed brain-insights skill",
          path: skillPath,
        };
      }
      return {
        success: true,
        message: "Brain-insights skill not found, nothing to remove",
      };
    }
    case "agents_file": {
      return removeFromAgentsFile(options);
    }
    default: {
      return {
        success: false,
        message: `Unknown injection method: ${method}`,
      };
    }
  }
}

/**
 * Check current injection status
 */
export function getInjectionStatus(options: PromptInjectionConfig = {}): {
  skillExists: boolean;
  skillPath: string;
  agentsHasSection: boolean;
  agentsPath: string;
} {
  const { skillDir = DEFAULT_SKILL_DIR, agentsFilePath = AGENTS_FILE_PATH } =
    options;
  const skillPath = path.join(skillDir, "SKILL.md");

  const skillExists = fs.existsSync(skillPath);

  let agentsHasSection = false;
  if (fs.existsSync(agentsFilePath)) {
    const content = fs.readFileSync(agentsFilePath, "utf8");
    agentsHasSection = content.includes(AGENTS_MARKER_START);
  }

  return {
    skillExists,
    skillPath,
    agentsHasSection,
    agentsPath: agentsFilePath,
  };
}

// =============================================================================
// Helpers
// =============================================================================

function escapeRegex(str: string): string {
  return str.replaceAll(/[$()*+.?[\\\]^{|}]/g, String.raw`\$&`);
}
